### ISSUE TITLE
Start/end year not working correctly

### ISSUE THREAD

**Issue by tjaffee99** [nlpaueb/edgar-crawler#11]
I'm trying to use edgar-crawler to create a data source of all 10-Ks for NLP embedding purposes. The default start-year and end-year are both 2021. When I attempted to change the start-year to 1993 and 1994, and the end-year to 2023, it still only downloaded the files from 2021. This happened both when I changed them from the command line and from the config.json file. Is there a way to fix this?

**Comment by eloukas** [comment]
Hi @tjaffee99, can you please share with me your `config.json` file so I can have a look at it? 
Thanks.

**Comment by tjaffee99** [comment]
I managed to get it to download all years. It appears to be an issue in my environment.

**Comment by eloukas** [comment]
I'm happy to hear that @tjaffee99.
Please ping me for anything other you might need!
