### ISSUE TITLE
Parallelism not working

### ISSUE THREAD

**Issue by ureshvahalia** [nlpaueb/edgar-crawler#14]
In edgar_crawler.py, it appears we are trying to issue number of downloads in parallel by creating a list_of_series in main. However, the way get_specific_indices() is coded, it returns a df with one entry per filing, so list_of_series is really a list of single-item entries. Hence crawl is called separately for each filing to download, which seems very slow. Am I missing something? Is this a bug or intentional for some reason?

**Comment by eloukas** [comment]
Hi @ureshvahalia, this is true: the method is called for a single-item entries. 

In a previous software version, I did have multiple-item lists but I found that this started to request the EDGAR database too quick and caused a temporary suspension of my IP. Thus, I've defaulted it to one entry per filing, which is safe according to their policy.
