### ISSUE TITLE
serious issues of 10-Q extraction: Item 1 Financial statements and Item 2 MD&A are gathered together

### ISSUE THREAD

**Issue by hahoangnhan** [nlpaueb/edgar-crawler#22]
Dear the team, 

I am checking the parsing output of 10-Qs and seeing all item_2 MD&A are gathered together with item_1. 
This is because the 10-Qs have two items 2. 
1. Item 2 The MD&A in Part I 
2. Item 2  Unregistered Sales of Equity Securities in Part II

I got the items 1 and 2 in Part 1 gathered for all of the 10-Qs, resulting in the MD&A appearing in the text of Item_1 Financial Statements. 
Can you check that? I am in a hurry for my research project, so any updates would be highly appreciated. 

Best, 
HHN

**Comment by eloukas** [comment]
@hahoangnhan The software does not currently support 10-Q extraction, as mentioned in the README.

**Comment by hahoangnhan** [comment]
> @hahoangnhan The software does not currently support 10-Q extraction, as mentioned in the README.

I got that. So it's not a real issue, but I hope to see any improvement in the future. 
Thank you so much!
HHN
