### ISSUE TITLE
Extracting sections for 10Q 

### ISSUE THREAD

**Issue by Sindhuja217** [nlpaueb/edgar-crawler#24]
Is there any way I can implement this on Form 10Q  to extract the textual data from the sections

**Comment by eloukas** [comment]
Hi @Sindhuja217, this is a feature we are currently working on and will be released in the following weeks. 
Make sure to "watch" the repo for the upcoming updates!

**Comment by eloukas** [comment]
@Sindhuja217  @hohoCode We updated the toolkit and it now supports 10-q extraction!
