### ISSUE TITLE
errno 22 

### ISSUE THREAD

**Issue by nyssarex** [nlpaueb/edgar-crawler#4]
with open(filepath, 'wb') as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Amir\\PycharmProjects\\edgar-crawler\\datasets\\RAW_FILINGS\\1020214_10K_1999_https://www.txt'

**Comment by nyssarex** [comment]
I am using windows+pycharm

**Comment by eloukas** [comment]
Hi @nyssarex, can you tell me in which line does this error occur? 
Also, some other users have solved it by replacing `://`" with `_`" in the filename.

I have tested the tool only in a Unix system. I will have a look into it for Windows as well and keep you updated.

**Comment by nyssarex** [comment]
@eloukas Hi again, I solved this error by this line guys 
accession_num = accession_num.replace("://", "_")  may be need to do test check on windows also, I am not sure this is a right solution

**Comment by eloukas** [comment]
Hi @nyssarex. 
Thank you for pointing out the issue. I fixed it and updated the code.
Feel free to open any new issue if anything arises.
