### ISSUE TITLE
An issue of cik_tickers in edgar_crawler.py

### ISSUE THREAD

**Issue by dnguyen-td** [nlpaueb/edgar-crawler#8]
Hi,

I edited the `config.json` file as suggested as follows.  I only choose two companies (CIKs) to test because I would like to see the format of raw fillings and where they are located.

`{'edgar_crawler': {'start_year': 2021,
  'end_year': 2021,
  'quarters': [1, 2, 3, 4],
  'filing_types': '10-K',
  'cik_tickers': ['1318605', '1018724'],
  'user_agent': 'myemail@gmail.com',
  'raw_filings_folder': 'RAW_FILINGS',
  'indices_folder': 'INDICES',
  'filings_metadata_file': 'FILINGS_METADATA.csv',
  'skip_present_indices': True},
 'extract_items': {'raw_filings_folder': 'RAW_FILINGS',
  'extracted_filings_folder': 'EXTRACTED_FILINGS',
  'filings_metadata_file': 'FILINGS_METADATA.csv',
  'items_to_extract': ['1', '1A', '7', '8'],
  'remove_tables': True,
  'skip_extracted_filings': True}}`

Next, I executed the `edgar_crawler.py` file and an error popped up.  I am not sure I understand the error here. Could you please help me or give me some suggestions to debug?

[run_edgar_crawler - Jupyter Notebook.pdf](https://github.com/nlpaueb/edgar-crawler/files/9765919/run_edgar_crawler.-.Jupyter.Notebook.pdf)

Thank you so much for your help.
Jun

**Comment by eloukas** [comment]
Hi @dnguyen-td ,

the error is in `filing_types` and not in `cik_tickers`.
As explained in the documentation, you need to pass a **list** there (even with a single element) **instead of a string** as you passed there.

I also updated the issue title to be more relevant for next users.
Thank you!
